<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql psycopg2-binary > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql+psycopg2://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql+psycopg2://postgres:***@localhost:5432/contoso_100k'

In [3]:
%%sql

SELECT DISTINCT
  continent
FROM
  customer

Running query in 'postgresql+psycopg2://postgres:***@localhost:5432/contoso_100k'

3 rows affected.

       continent
0      Australia
1  North America
2         Europe

In [14]:
%%sql

SELECT
  s.orderdate,
  COUNT(DISTINCT s.customerkey) AS total_customers,
  COUNT(DISTINCT CASE WHEN  c.continent = 'Europe' THEN s.customerkey END) AS eu_continent,
  COUNT(DISTINCT CASE WHEN  c.continent = 'Australia' THEN s.customerkey END) AS na_continent,
  COUNT(DISTINCT CASE WHEN  c.continent = 'North America' THEN s.customerkey END) AS au_continent

FROM
  sales s
LEFT JOIN customer c ON s.customerkey = c.customerkey
WHERE
    s.orderdate BETWEEN '2023-01-01' AND '2023-12-31'
GROUP BY
  s.orderdate
ORDER BY
  s.orderdate

Running query in 'postgresql+psycopg2://postgres:***@localhost:5432/contoso_100k'

364 rows affected.

      orderdate  total_customers  eu_continent  na_continent  au_continent
0    2023-01-01               12             6             1             5
1    2023-01-02               49            15             3            31
2    2023-01-03               64            17             3            44
3    2023-01-04               78            28             4            46
4    2023-01-05               87            22             8            57
..          ...              ...           ...           ...           ...
359  2023-12-27               73            26             6            41
360  2023-12-28               75            24             7            44
361  2023-12-29               55            19             4            32
362  2023-12-30               91            25            16            50
363  2023-12-31                9             1             0             8

[364 rows x 5 columns]

In [15]:
%%sql

SELECT *
FROM
  sales

Running query in 'postgresql+psycopg2://postgres:***@localhost:5432/contoso_100k'

199873 rows affected.

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64
1,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64
2,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.38,54.38,25.00,USD,1.00
3,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.04,286.69,144.88,USD,1.00
4,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.75,135.75,62.43,USD,1.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
199868,3398034,1,2024-04-20,2024-04-21,664396,999999,1651,7,159.99,139.19,73.57,EUR,0.94
199869,3398034,2,2024-04-20,2024-04-21,664396,999999,1646,1,159.99,159.99,73.57,EUR,0.94
199870,3398035,0,2024-04-20,2024-04-22,267690,999999,1575,2,60.99,53.67,28.05,CAD,1.38
199871,3398035,1,2024-04-20,2024-04-22,267690,999999,415,5,326.00,293.40,166.20,CAD,1.38
199872,3398035,2,2024-04-20,2024-04-22,267690,999999,1693,6,6.88,6.88,3.16,CAD,1.38