<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [42]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql psycopg2-binary > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql+psycopg2://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

Connecting and switching to connection 'postgresql+psycopg2://postgres:***@localhost:5432/contoso_100k'

Average, MIN, MAX revenue by year by category

In [49]:
%%sql

SELECT
  p.categoryname AS category,
  MIN(CASE WHEN s.orderdate BETWEEN '2022-01-01' AND '2022-12-31' THEN (s.netprice*s.exchangerate*s.quantity) END) AS min_revenue_2022,
  AVG(CASE WHEN s.orderdate BETWEEN '2022-01-01' AND '2022-12-31' THEN (s.netprice*s.exchangerate*s.quantity) END) AS avg_revenue_2022,
  MAX(CASE WHEN s.orderdate BETWEEN '2022-01-01' AND '2022-12-31' THEN (s.netprice*s.exchangerate*s.quantity) END) AS max_revenue_2022,
  MIN(CASE WHEN s.orderdate BETWEEN '2023-01-01' AND '2023-12-31' THEN (s.netprice*s.exchangerate*s.quantity) END) AS min_revenue_2023,
  AVG(CASE WHEN s.orderdate BETWEEN '2023-01-01' AND '2023-12-31' THEN (s.netprice*s.exchangerate*s.quantity) END) AS avg_revenue_2023,
  MAX(CASE WHEN s.orderdate BETWEEN '2023-01-01' AND '2023-12-31' THEN (s.netprice*s.exchangerate*s.quantity) END) AS max_revenue_2023
FROM
  sales s
  LEFT JOIN product p ON s.productkey = p.productkey
GROUP BY
  p.categoryname
ORDER BY
  p.categoryname

Running query in 'postgresql+psycopg2://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,category,min_revenue_2022,avg_revenue_2022,max_revenue_2022,min_revenue_2023,avg_revenue_2023,max_revenue_2023
0,Audio,9.31,392.30,3473.36,10.85,425.38,2730.87
1,Cameras and camcorders,6.74,1210.02,15008.39,5.98,1210.96,13572.00
2,Cell phones,2.53,722.20,7692.37,2.28,623.28,8912.22
3,Computers,0.83,1565.62,38082.66,0.75,1292.39,27611.60
4,Games and Toys,2.83,81.29,5202.01,3.49,80.83,3357.30
5,Home Appliances,4.04,1755.36,31654.55,4.54,1886.55,32915.59
6,"Music, Movies and Audio Books",7.29,386.61,5415.19,6.91,334.58,3804.91
7,TV and Video,41.30,1535.61,30259.41,42.30,1687.90,27503.12

In [50]:
# Median values, arrange it in order and then pick the middle one if not odd numbers pick the center two and get their avg

In [54]:
%%sql

SELECT
    #  PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY salary DESC) "Median cont", SYNTAX
     PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY netprice DESC) AS "Median cont"
FROM
  sales

Running query in 'postgresql+psycopg2://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

   Median cont
0       191.95

In [58]:
%%sql

SELECT
  p.categoryname AS category,
  # MIN(CASE WHEN s.orderdate BETWEEN '2022-01-01' AND '2022-12-31' THEN (s.netprice*s.exchangerate*s.quantity) END) AS min_revenue_2022,
  PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (CASE WHEN s.orderdate BETWEEN '2022-01-01' AND '2022-12-31' THEN (s.netprice*s.exchangerate*s.quantity) END)) AS Y2022_median,
  PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (CASE WHEN s.orderdate BETWEEN '2023-01-01' AND '2023-12-31' THEN (s.netprice*s.exchangerate*s.quantity) END)) AS Y2023_median
FROM
  sales s
  LEFT JOIN product p ON s.productkey = p.productkey
GROUP BY
  p.categoryname
ORDER BY
  p.categoryname

Running query in 'postgresql+psycopg2://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                        category  y2022_median  y2023_median
0                          Audio        257.21        266.59
1        Cameras and camcorders         651.46        672.60
2                    Cell phones        418.60        375.88
3                      Computers        809.70        657.18
4                 Games and Toys         33.78         32.62
5                Home Appliances        791.00        825.25
6  Music, Movies and Audio Books        186.58        159.63
7                   TV and Video        730.46        790.79

Advance agregations, using multiple AND statements in CASE WHEN, and segmenting it down.

In [62]:
%%sql

SELECT
  PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (s.netprice*s.exchangerate*s.quantity)) AS median
FROM
  sales s
WHERE
  s.orderdate BETWEEN '2022-01-01' AND '2023-12-31'

Running query in 'postgresql+psycopg2://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

   median
0  398.00

In [80]:
%%sql

# instead of hardcoding median values "398" it will use this as function to calculate it

WITH median_calculation AS(
  SELECT
  PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (s.netprice*s.exchangerate*s.quantity)) AS median
  FROM
    sales s
  WHERE
    s.orderdate BETWEEN '2022-01-01' AND '2023-12-31'
)

SELECT
  p.categoryname AS category,
  # low_high median for 2022
  SUM(CASE
        WHEN s.netprice*s.exchangerate*s.quantity < mv.median AND s.orderdate BETWEEN  '2022-01-01' AND '2022-12-31'
        THEN s.netprice*s.exchangerate*s.quantity END) AS low_median_value_2022,
  SUM(CASE
        WHEN s.netprice*s.exchangerate*s.quantity >= mv.median AND s.orderdate BETWEEN  '2022-01-01' AND '2022-12-31'
        THEN s.netprice*s.exchangerate*s.quantity END) AS high_median_value_2022,

         # low_high median for 2023
  SUM(CASE
        WHEN s.netprice*s.exchangerate*s.quantity < mv.median AND s.orderdate BETWEEN  '2023-01-01' AND '2023-12-31'
        THEN s.netprice*s.exchangerate*s.quantity END) AS low_median_value_2023,
  SUM(CASE
        WHEN s.netprice*s.exchangerate*s.quantity >= mv.median AND s.orderdate BETWEEN  '2023-01-01' AND '2023-12-31'
        THEN s.netprice*s.exchangerate*s.quantity END) AS high_median_value_2023
FROM
  sales s
  LEFT JOIN product p ON s.productkey = p.productkey,
  median_calculation mv
GROUP BY
  p.categoryname
ORDER BY
  p.categoryname

Running query in 'postgresql+psycopg2://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,category,low_median_value_2022,high_median_value_2022,low_median_value_2023,high_median_value_2023
0,Audio,222337.83,544600.39,180251.13,508439.06
1,Cameras and camcorders,133004.54,2249528.02,104869.46,1878676.83
2,Cell phones,814449.53,7305215.55,729699.39,5272448.24
3,Computers,624340.42,17237873.07,590790.31,11060076.90
4,Games and Toys,231979.63,84147.67,206103.36,64271.60
5,Home Appliances,219797.07,6392649.61,176261.35,5743731.52
6,"Music, Movies and Audio Books",685808.49,2303488.80,574958.76,1605809.37
7,TV and Video,272338.29,5542998.32,164275.35,4247902.87

In [96]:
%%sql

# instead of hardcoding median values "398" it will use this as function to calculate it


WITH percentile_cal AS(
  SELECT
    PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY (s.netprice*s.exchangerate*s.quantity)) AS rev_25th_percentile,
    PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY (s.netprice*s.exchangerate*s.quantity)) AS rev_75th_percentile
  FROM
    sales s
  WHERE
    s.orderdate BETWEEN '2022-01-01' AND '2023-12-31'
)

SELECT
  p.categoryname AS category,
  CASE
    WHEN (s.netprice*s.exchangerate*s.quantity) < rev_25th_percentile THEN '1 - LOW'
    WHEN (s.netprice*s.exchangerate*s.quantity) >= rev_75th_percentile THEN '3 - HIGH'
    ELSE '2 - MEDIUM'
    END AS revenue_tier,
  SUM(s.netprice*s.exchangerate*s.quantity) AS total_revenue
FROM
  sales s
  LEFT JOIN product p ON s.productkey = p.productkey,
  percentile_cal ptcl

GROUP BY
  p.categoryname,
  revenue_tier
ORDER BY
  p.categoryname,
  revenue_tier

Running query in 'postgresql+psycopg2://postgres:***@localhost:5432/contoso_100k'

24 rows affected.

                         category revenue_tier  total_revenue
0                           Audio      1 - LOW      267217.01
1                           Audio   2 - MEDIUM     3832415.38
2                           Audio     3 - HIGH     1213265.71
3         Cameras and camcorders       1 - LOW       81032.92
4         Cameras and camcorders    2 - MEDIUM     3388546.10
5         Cameras and camcorders      3 - HIGH    15050781.63
6                     Cell phones      1 - LOW      410309.35
7                     Cell phones   2 - MEDIUM    10338963.22
8                     Cell phones     3 - HIGH    21874993.15
9                       Computers      1 - LOW      203207.06
10                      Computers   2 - MEDIUM    10808054.11
11                      Computers     3 - HIGH    79607760.89
12                 Games and Toys      1 - LOW      533443.13
13                 Games and Toys   2 - MEDIUM     1001381.91
14                 Games and Toys     3 - HIGH      133749.09
15                Home Appliances      1 - LOW      105045.60
16                Home Appliances   2 - MEDIUM     4118724.64
17                Home Appliances     3 - HIGH    22383475.30
18  Music, Movies and Audio Books      1 - LOW      642496.71
19  Music, Movies and Audio Books   2 - MEDIUM     6100817.99
20  Music, Movies and Audio Books     3 - HIGH     3844996.29
21                   TV and Video      1 - LOW       67221.76
22                   TV and Video   2 - MEDIUM     3766783.30
23                   TV and Video     3 - HIGH    16632856.33